apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-tech-orders-api
  labels:
    app: move-tech-orders-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: move-tech-orders-api
  template:
    metadata:
      labels:
        app: move-tech-orders-api
    spec:
      imagePullSecrets:
        - name: mgc-registry-secret

      containers:
        - name: move-tech-orders-api
          image: container-registry.br-se1.magalu.cloud/hrrogerio/move-tech-orders-api:latest
          imagePullPolicy: Always

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url

          ports:
            - containerPort: 8000
              name: http

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: move-tech-orders-api
spec:
  selector:
    app: move-tech-orders-api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
